### ISSUE TITLE
Desktop Data from 2017-01 missing

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#116] opened 2017-06-14 13:51 UTC
I've needed to reimport some data and it looks like the desktop runs (pages.csv) from 1st and 15th Jan is missing. Can they be recreated?

**Comment by rviscomi** [comment] 2017-06-14 20:42
I think this is a duplicate of https://github.com/HTTPArchive/httparchive/issues/74

**Comment by Themanwithoutaplan** [comment] 2017-06-15 07:29
It may be related but it's not a duplicate. The downloads page lists January 2017 but the links are broken. The thing is that the dumps were available at the time and contained valid data. Can they be recreated?

**Comment by rviscomi** [comment] 2019-02-04 23:21
Combining with #74

**Closed by rviscomi** 2019-02-04 23:21 UTC
