### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/legacy.httparchive.org#152] opened 2018-08-15 11:01 UTC
The FAQs are missing some updates in the change log and, more importantly, a note on the change on the source of the top 1,000,000 websites from 2018-07-01.

**Comment by rviscomi** [comment] 2018-08-15 18:44
Thanks @Themanwithoutaplan! Closing this as a duplicate of https://github.com/HTTPArchive/httparchive.org/issues/53

**Closed by rviscomi** 2018-08-15 18:44 UTC
Labels: duplicate
