### ISSUE TITLE
May `android_requests_bodies` tables showing suspiciously few results

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/legacy.httparchive.org#113] opened 2017-06-06 18:31 UTC
For example:

```sql
SELECT UNIQUE(page) FROM [httparchive:har.2017_04_15_android_requests_bodies] WHERE body CONTAINS "sw-precache-v"
```

Querying the 4/15 data shows 111 rows, whereas 5/01 and 5/15 are only showing 1 row each.

I looked at the relative sizes of the tables and they seem comparable (~700GB).

**Comment by rviscomi** [comment] 2017-06-06 19:37
```sql
SELECT page, url, body FROM [httparchive:har.2017_04_15_android_requests_bodies] WHERE page = 'http://www.kiwi.com/' AND url CONTAINS 'service-worker'
```

1 result.

Changing to 05_15: 0 results, despite the request existing in waterfall http://httparchive.webpagetest.org/result/170515_37_FTGW/1/details/#step1_request20

**Comment by rviscomi** [comment] 2017-06-06 19:49
The SW request exists in the `requests_mobile` table:

```sql
SELECT * FROM [httparchive:runs.2017_05_15_requests_mobile] WHERE url = 'https://www.kiwi.com/service-worker.js'
```

Incidentally, there are two results because we're testing both kiwi.com and skypicker.com, the latter redirects to the former.


So how can we have a JS request but not its response body?

**Comment by pmeenan** [comment] 2017-06-06 20:39
Suspiciously few results in general or just for the service worker js?  We rely on dev tools for getting response bodies and all of the service worker stuff is completely hidden from dev tools (we can get the timings for them because we also get the netlogs).

**Comment by rviscomi** [comment] 2017-06-06 20:46
In this incredibly scientific study there are hundreds fewer requests containing a sample string:

`SELECT COUNT(0) FROM [httparchive:har.2017_04_15_chrome_requests_bodies] WHERE body CONTAINS "foobar"`: 9998
`SELECT COUNT(0) FROM [httparchive:har.2017_05_01_chrome_requests_bodies] WHERE body CONTAINS "foobar"`: 9312
`SELECT COUNT(0) FROM [httparchive:har.2017_05_15_chrome_requests_bodies] WHERE body CONTAINS "foobar"`: 9496

More dramatic on mobile:

`SELECT COUNT(0) FROM [httparchive:har.2017_04_15_android_requests_bodies] WHERE body CONTAINS "foobar"`: 9466
`SELECT COUNT(0) FROM [httparchive:har.2017_05_01_android_requests_bodies] WHERE body CONTAINS "foobar"`: 8626
`SELECT COUNT(0) FROM [httparchive:har.2017_05_15_android_requests_bodies] WHERE body CONTAINS "foobar"`: 8558

So doesn't seem to be limited to SW JS unless `foobar` is biased towards SW ;)

**Comment by rviscomi** [comment] 2017-06-06 21:11
Not really sure of the best way to test for this.

Here's the % of Android request bodies for URLs ending in CSS (something not JS related):

```
4/01	4/15	5/01	5/15
18.681	18.579	17.477	17.416
```

There's clearly a drop on 5/01. And that reminds me that there is a noticeable drop on 5/01 for the JS bytes charts too: http://jsfiddle.net/rviscomi/1r6dpctd/show/

**Comment by pmeenan** [comment] 2017-06-06 21:45
If you could get some specific pages where css or js bodies aren't showing up then I can debug it.  It could be something with the retrieving of the content type to determine if it should get the body but that is likely a separate issue from the JS/CSS drop.

[Here](https://github.com/WPO-Foundation/wptagent/blob/master/internal/devtools.py#L284) is the logic for pulling bodies.  I can open it up and be less restrictive but I'm trying to avoid pulling something like a video stream by accident.  Once it decides to pull a body from Chrome, as long as it isn't base64-encoded it keeps it (that could also be a possible issue depending on the encoding)

**Comment by rviscomi** [comment] 2017-06-07 15:14
> some specific pages where css or js bodies aren't showing up
See kiwi.com test from https://github.com/HTTPArchive/httparchive/issues/113#issuecomment-306594448

**Comment by pmeenan** [comment] 2017-06-07 17:12
Sorry, a js file other than a serviceworker one.  Those are expected to be missing.  It looks like for kiwi.com, [run#3](http://httparchive.webpagetest.org/result/170515_37_FTGW/3/details/#waterfall_view_step1) was the median run and it looks like we got bodies for the requests (though something seems to be up with the alignment that I need to look into).

**Comment by rviscomi** [comment] 2017-06-07 19:04
Why are SW expected to be missing?

On [4/15](http://httparchive.webpagetest.org/result/170415_37_FT9V/2/details/#step1_request15) the SW response was in the response bodies zip as `015-23-body.txt`. Not sure what the "23" is referring to, but I assume "015" represents that it was the 15th request.

On [5/15](http://httparchive.webpagetest.org/result/170515_37_FTGW/3/details/#step1_request15) the SW was still the 15th request, but the contents of the `015-15227.150-body.txt` file are just `{}`. It seems like this is the response for the `https://logg.kiwi.com/logmole` request. Not sure what "15227" represents, but all files have that in their name. I browsed all response bodies for this run and none of them contained the SW.

So something seems to be off about the 5/15 run both in terms of file naming scheme and the response bodies getting dropped entirely.

**Comment by pmeenan** [comment] 2017-06-08 00:45
015 is 15th request, 23 is the request ID.  In the new agent where we use dev tools, the request ID's are floating point numbers (15227.150), you should see the same number as the request ID's for the requests.

The old Windows agent intercepted the network traffic which is how it has the sw bodies.  The new agent uses Chrome's built-in support in dev tools but SW is invisible to dev tools so no bodies for them.  

That said, there are a lot of others missing so there is probably something else with the filtering on my side.

**Comment by jeffposnick** [comment] 2017-06-09 18:17
Thanks for investigating this, @rviscomi!

@pmeenan, our team found access to the service workers' bodies in the HTTP Archive very useful—we develop SW libraries, and SW usage across the top sites was an important metric for us.

I believe that there's at least some degree of interaction between SW request bodies and DevTools. You can, for instance, see requests for both the top-level SW scripts and any fetches that originate from the SW in the [Network panel of the DevTools UI](https://stackoverflow.com/questions/33590378/status-code200-ok-from-serviceworker-in-chrome-network-devtools/33655173#33655173).

I don't know how, exactly, that translates into information exposed via the DevTools debugging protocols, but we could probably find the right folks to loop in and find out if you'd find that helpful as a next step.

CC: @addyosmani @gauntface

**Comment by addyosmani** [comment] 2017-06-10 01:06
As we're talking about the DevTools debugging protocol, going to cc in @paulirish @samccone and @kdzwinel just in case they might be able to add some color to the discussion.

**Comment by rviscomi** [comment] 2017-07-13 21:30
Is there a FR somewhere to get SW exposed in dev tools debugging protocol?

Pat, did you find out anything else with the other missing responses? I can dig up example URLs if it'll be helpful.

**Comment by jeffposnick** [comment] 2017-07-14 15:52
I don't pretend to understand the DevTools debugging protocol, but there's some service worker-specific interfaces at https://chromedevtools.github.io/devtools-protocol/tot/ServiceWorker/

Like I mentioned, you do see entries, including request/response bodies, for SW-originated requests in the DevTool's Network panel when you look manually. Assuming the DevTools Network panel is using the same public debugging protocol under the hood, that data should be exposed.

**Comment by pmeenan** [comment] 2017-07-14 16:49
I sent the team a question to see how they collect it.  The ServiceWorker interfaces don't do anything for requests and the SW requests don't show up in the Network.* events for a given tab (and there doesn't appear to be a tab specific to the service worker to connect to).

**Comment by pmeenan** [comment] 2017-07-18 15:38
I just landed the code to pull bodies from sw-initiated requests (including the service worker itself).  We're ~3 days into the current crawl so it will have partial data (with the August 1 crawl having the full set of bodies).

**Comment by jeffposnick** [comment] 2017-07-18 15:40
Great news, @pmeenan! Thanks for taking care of that.

**Comment by rviscomi** [comment] 2017-07-18 15:50
Thanks Pat!

> That would work for Service workers, dedicated workers, out of process iframes.
>
> https://github.com/ChromeDevTools/devtools-protocol/issues/36#issuecomment-315421588

Could the iframe bit explain why we saw a drop in both JS and CSS bytes?

**Comment by pmeenan** [comment] 2017-07-18 16:02
Right now I'm explicitly only attaching to service_worker target types.  I haven't seen any issues with iFrames and response bodies but it's possible I just haven't tripped over any cases of out-of-process iFrames.  The strings for the target types aren't documented so I'm a bit hesitant to just add more targets without being able to debug them locally first.

If you can find failcases with missing bodies I'm happy to look into and fix them.

**Comment by pmeenan** [comment] 2017-07-18 16:06
FWIW, I also found and fixed the issue that was mixing up response bodies for some requests.  When we switched to floating point request ID's from dev tools, the php code was doing numerical comparisons instead of string comparisons so for request ID 123.40 it would return the body for 123.4 - argh

**Comment by pmeenan** [comment] 2017-07-18 16:08
BTW, nothing bodies related should have an impact on the byte counts.  We parse the netlog events from the trace so we can see all of the requests regardless of where they are issued and we calculate the bytes transferred from there.  

The total bytes looks historically consistent but the HTML, JS and CSS mime-specific bytes look off so my guess is somewhere on the mime type extraction/mapping.  Again, failcases would really help so we can see what the WebPageTest UI thinks the content type is for a given request.

**Comment by rviscomi** [comment] 2017-07-18 16:39
I'll dig up some failcases and report back.

**Comment by rviscomi** [comment] 2017-07-18 16:45
I should clarify that https://github.com/HTTPArchive/httparchive/issues/113#issuecomment-306618593 measured the count of CSS response bodies themselves, not bytes. So while there is a possibly unrelated byte deficit in some cases, the bodies of non-JS responses are affected as well. That leads me to think there's something else about the dev tools extraction causing a blindspot besides SW.

**Comment by rviscomi** [comment] 2017-07-18 19:31
http://www.tsrhc.org/css/dropkick.css

- Exists in both the [4/15](http://httparchive.webpagetest.org/result/170415_5N_VP7Q/1/details/#step1_request7) and [5/1](http://httparchive.webpagetest.org/result/170501_66_YA8V/2/details/#step1_request4) WPT waterfalls.
- Exists in both the `2017_04_15_android_requests` and `2017_05_01_android_requests` tables.
- Exists in the `2017_04_15_android_requests_bodies` table but **not** in the `2017_05_01_android_requests_bodies` table.

Let me know if you need more.


FWIW, the number of CSS requests missing bodies was ~40k on 4/15 and ~214k on 5/1. Example query:

```sql
SELECT
  url
FROM
  [httparchive:runs.2017_04_15_requests_mobile]
WHERE
  mimeType = 'text/css' AND
  url NOT IN (
  SELECT
    url
  FROM
    [httparchive:har.2017_04_15_android_requests_bodies])
```

**Comment by pmeenan** [comment] 2017-07-18 20:35
Do yoy know that page it came from?

**Comment by pmeenan** [comment] 2017-07-18 20:36
Checking http://www.tsrhc.org/ just in case right now.

**Comment by pmeenan** [comment] 2017-07-18 20:38
At least testing on the public WPT with the Linux agent it looks like the body for dropkick.css is being collected now: http://www.webpagetest.org/result/170718_2K_8d5aee618baf392bedcd8c000f976609/1/details/#step1_request6 (not sure if it wasn't before though - will have to keep an eye on the crawl).

**Comment by rviscomi** [comment] 2017-07-19 16:25
Yeah it looks like the response body wasn't saved in the 5/1 crawl: http://httparchive.webpagetest.org/result/170501_66_YA8V/2/details/#step1_request4. Many (but not all) of the CSS/JS requests are missing response bodies. Is this just a symptom of https://github.com/HTTPArchive/httparchive/issues/113#issuecomment-316113243?

The body is available in the 4/15 crawl: http://httparchive.webpagetest.org/result/170415_5N_VP7Q/1/details/#step1_request7. The requests seem to more consistently have response bodies. Still found some without it.

**Comment by pmeenan** [comment] 2017-07-19 16:51
It's possible.  I also changed the agent to collect bodies for each request as soon as the request completes instead of at the end of the test in case Chrome was recycling them.

**Comment by rviscomi** [comment] 2017-09-05 18:24
>  I also changed the agent to collect bodies for each request as soon as the request completes instead of at the end of the test in case Chrome was recycling them.

@pmeenan this may have adversely affected the total response bodies collected. Starting on 7/15 we're getting fewer mobile response bodies. Desktop seems ok.

date | client | rows
-- | -- | --
2017/08/15 | android | 11227233
2017/08/15 | chrome | 17234722
2017/08/01 | android | 11607360
2017/08/01 | chrome | 17657463
2017/07/15 | android | **11499506**
2017/07/15 | chrome | 17597889
2017/07/01 | android | 15367330
2017/07/01 | chrome | 16716581
2017/06/15 | android | 15598792
2017/06/15 | chrome | 16702320
2017/06/01 | android | 15408366
2017/06/01 | chrome | 16517787
2017/05/15 | android | 15617182
2017/05/15 | chrome | 16441204
2017/05/01 | android | 15630932
2017/05/01 | chrome | 16478928
2017/04/15 | android | 15600005
2017/04/15 | chrome | 16896356
2017/04/01 | android | 15721474
2017/04/01 | chrome | 17095966

**Comment by pmeenan** [comment] 2017-09-05 18:47
The desktop/mobile logic is identical so there shouldn't be a difference from that specifically.  There were a couple of more recent fixes with response bodies in HARs which may improve things.  If we can track down pages where a js, html or css body isn't available I can try to reproduce (maybe best to wait for the 9/1 run).

That said, one of the fixes was an issue that has been in the code forever where it may have been giving non-text resources the bodies from some text resources and over-inflating the counts.

**Comment by rviscomi** [comment] 2017-09-06 17:57
Here's a page that shows a mysterious drop in response bodies:

```
SELECT
  COUNT(0)
FROM
  [httparchive:har.2017_07_01_android_requests_bodies]
WHERE
  page = 'http://www.fuller.edu/'
```

The count of response bodies on 7/1 is 135. A similar query for 7/15 shows 42 bodies.

The corresponding WPT results: [7/1](http://httparchive.webpagetest.org/result/170701_S_3V73/3/details/) and [7/15](http://httparchive.webpagetest.org/result/170715_T_3Z52/1/details/).

For example, "dragdrop.js" is present in both tests and has similar response characteristics but it's only showing up in the 7/1 table. FWIW I also checked the 8/15 table and it's still missing from there but present in the [WPT results](http://httparchive.webpagetest.org/result/170801_V_47YE/2/details/#step1_request154), so the bug seems to be more deterministic than not.

@pmeenan  is that enough to go on?

**Comment by pmeenan** [comment] 2017-09-06 18:39
My guess is that it is related to [this](https://github.com/WPO-Foundation/webpagetest/commit/505242c941a7198f567fb9e5a70c423bf7a47010) which was fixed on August 21.  It impacts the new agent more than the old because the bodies tend to be utf8-encoded already (which would have been dropped).

That said, The 7/15 crawl actually had the body and still wasn't exporting locally so I cleaned up the logic some more and it should get incrementally better again after the 9/15 crawl.

I verified that the fix is [correctly including](http://httparchive.webpagetest.org/export.php?bodies=1&pretty=1&test=170715_T_3Z52) the dragdrop.js body from the 7/15 crawl now.

**Comment by pmeenan** [comment] 2017-09-06 18:40
And thanks for the failcase - examples make finding and fixing issues like this significantly easier.

**Comment by rviscomi** [comment] 2017-09-06 18:55
Great, thanks for looking into this. I'll keep an eye on the metrics over the next couple of crawls.

For my future self, here's the query to compare response bodies per page/extension over crawls:

```sql
SELECT
  before.page,
  before.ext,
  before.n - after.n AS diff,
  before.n, after.n
FROM (
  SELECT
    page,
    REGEXP_EXTRACT(url, '.*/[^?&]*\\.([a-z]{2,4})') AS ext,
    COUNT(0) AS n
  FROM
    [httparchive:har.2017_07_01_android_requests_bodies]
  GROUP BY
    page,
    ext
  HAVING
    ext IN ('html',
      'css',
      'js')) AS before
JOIN (
  SELECT
    page,
    REGEXP_EXTRACT(url, '.*/[^?&]*\\.([a-z]{2,4})') AS ext,
    COUNT(0) AS n
  FROM
    [httparchive:har.2017_07_15_android_requests_bodies]
  GROUP BY
    page,
    ext
  HAVING
    ext IN ('html',
      'css',
      'js')) AS after ON before.page = after.page AND before.ext = after.ext
ORDER BY
  diff DESC
LIMIT 100
```

**Closed** 2019-02-04 23:15 UTC
Labels: bug
